config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'homes#top'
  get  'homes/about' => 'homes#about'
  post   '/favorite/:music_id' => 'favorites#favorite',   as: 'favorite'
  delete '/favorite/:music_id' => 'favorites#unfavorite', as: 'unfavorite'
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す

  resources :musics do
  	resource :comments, only: [:create]
  end
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :user
    belongs_to :music
end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :music, counter_cache: :favorites_count
    belongs_to :user
end

app/models/genre.rb
class Genre < ApplicationRecord

	has_many :musics
end

app/models/music.rb
class Music < ApplicationRecord

	belongs_to :genre
	belongs_to :user
    has_many :favorites, dependent: :destroy
	attachment :album_image
	has_many :comments, dependent: :destroy

    validates :singer, presence: true
    validates :album, presence: true
    validates :rate, presence: true
    validates :url, presence: true
    validates :introduction, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord

	belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :musics
  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorite_musics, through: :favorites, source: :music

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  attachment :profile_image

  validates :name, presence: true
  validates :introduction, length: { maximum: 55 }

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

  private
  # サインイン後のリダイレクト先
  def after_sign_in_path_for(resource)
      musics_path
  end

  # サインアウト後のリダイレクト先
  def after_sign_out_path_for(resource)
      root_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email,:profile_image,:introduction])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		music = Music.find(params[:music_id])
	    comment = current_user.comments.new(comment_params)
	    comment.music_id = music.id
	    comment.score = Language.get_data(comment_params[:comment])
	    comment.save
	    redirect_to music_path(music)
	end

	private
	def comment_params
	    params.require(:comment).permit(:user_id,:music_id,:comment)
	end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  before_action :set_variables

  def favorite
    favorite = current_user.favorites.new(music_id: @music.id)
    favorite.save
  end

  def unfavorite
    favorite = current_user.favorites.find_by(music_id: @music.id)
    favorite.destroy
  end

  private

  def set_variables
    @music = Music.find(params[:music_id])
    @id_name = "#favorite-link-#{@music.id}"
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def top
	end

	def about
	end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController

	before_action :authenticate_user!

	def index
		if params[:genre_id]
	      # Genreのデータベースのテーブルから一致するidを取得
	      @genre = Genre.find(params[:genre_id])
	      # genre_idと紐づく投稿を取得
	      @musics = @genre.musics.order(created_at: :desc).page(params[:page]).per(3)
	    else
	      # 投稿すべてを取得
	      @musics = Music.order(created_at: :desc).page(params[:page]).per(3)

	    end
	      @genres = Genre.all
	end

	def new
		@music = Music.new
	end

	def show
		@music = Music.find(params[:id])
        @comment = Comment.new
        @user = @music.user
	end

	def create
	    @music = Music.new(music_params)
	    @music.user_id = current_user.id
	 if @music.save
		redirect_to musics_path
	 else
		render 'new'
	 end
	end

	def edit
		@music = Music.find(params[:id])
	end

	def update
        @music = Music.find(params[:id])
     if @music.update(music_params)
        redirect_to musics_path
     else
        render 'edit'
     end
    end

    def destroy
       music = Music.find(params[:id])
       music.destroy
       redirect_to musics_path(@music)
    end

	private
    def music_params
        params.require(:music).permit(:singer, :album, :album_image, :introduction, :user_id, :rate, :url, :genre_id)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

	def follow
	  current_user.follow(params[:id])
	  redirect_to request.referer
	end

	def unfollow
	  current_user.unfollow(params[:id])
	  redirect_to request.referer
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!

	def index
		user = current_user
		@users = User.page(params[:page]).per(3).order('updated_at DESC')
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
    if  @user.id != current_user.id
        redirect_to user_path(current_user)
    end
	end

	def update
		@user = User.find(params[:id])
	if  @user.update(user_params)
	    redirect_to user_path(@user.id)
	else
	    render 'edit'
	end
	end

 private
	def user_params
	    params.require(:user).permit(:name, :profile_image,:introduction)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorites.html.erb
  <% if current_user.favorites.find_by(music_id: music.id) %>
    <%= link_to unfavorite_path(music.id), method: :delete, remote: true do %>
        <div class = "iine__button">❤️<%= music.favorites.count %></div>
    <% end %>
  <% else %>
    <%= link_to favorite_path(music.id), method: :post, remote: true do %>
        <div class = "iine__button">♡️<%= music.favorites.count %></div>
    <% end %>
  <% end %>

app/views/favorites/favorite.js.erb
$("#favorite-link-<%= @music.id %>").html('<%= j(render partial:"favorites/favorites",locals: {  music: @music }) %>');

app/views/favorites/unfavorite.js.erb
$("#favorite-link-<%= @music.id %>").html('<%= j(render partial:"favorites/favorites",locals: {  music: @music }) %>');

app/views/musics/_genre.html.erb
<div class='col-xs-2'>
<table class="table table-striped">
    <thead>
      <tr>
        <th>ジャンル検索</th>
      </tr>
    </thead>
    <tbody>
      <% @genres.each do |genre| %>
        <tr>
          <td><%= link_to genre.name, "/musics?genre_id=#{genre.id}",:style=>"color:red;" %></td>
        </tr>
      <% end %>
    </tbody>
</table>
</div>

app/views/musics/_musics.html.erb
<%= render 'favorites/favorite', music: music %>

app/views/musics/about.html.erb
musics#about

<h1>音楽を共有できるサイトです</h1>

app/views/musics/edit.html.erb
<div class="body">
  <div class="container">

    <% if @music.errors.any? %>
      <div id="error_explanation">
        <h3><%= @music.errors.count %> 件のエラーがあります:</h3>
        <ul>
          <% @music.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

<h2 align="center">アルバム編集</h2>
      <%= form_for(@music) do |f| %>
      <div class="row">
            <b>アルバム画像</b>
            <div id="image_view"></div>
            <%= attachment_image_tag @music, :album_image, :fill, 250, 250, fallback: "no_image.jpg", id:"orgin_img" %>
           <label for="image_btn">
            <%= f.attachment_field :album_image, id: "image_btn" %>
           </label>
        </div>
            <table class="table">
              <div class='col-xs-9'>
                <tbody>
                  <tr>
                    <td><b>アーティスト名</b></td>
                    <td><%= f.text_field :singer,placeholder: "アーティスト名入力" %></td>
                  </tr>
                  <tr>
                    <td><b>アルバム名</b></td>
                    <td><%= f.text_field :album,placeholder: "アルバム名入力" %></td>
                  </tr>
                  <tr>
                  <td><b>ジャンル</b></td>
                  <td><%= f.collection_select :genre_id, Genre.all, :id, :name, :include_blank => "-- 選択してください --" %></td>
                  </tr>

                  <tr>
                  <!-- 評価 -->
                    <td>
                      <div class="form-group row" id="star">
                          <%= f.label :rate,'評価', class:'col-md-1 col-form-label' %>
                          <%= f.hidden_field :rate, id: :review_star %>
                      </div>
                    </td>
                    </tr>
                  <tr>
                    <td><b>YouTubeのURL</b></td>
                    <td><%= f.text_area :url,placeholder: "URL入力" %></td>
                  </tr>
                  <tr>
                    <td><b>レビュー内容</b></td>
                    <td><%= f.text_area :introduction,placeholder: "レビュー内容" %></td>
                  </tr>
              </tbody>
             </div>
            </table>
            <%= f.submit '投稿する',class: "btn btn-success col-xs-4 col-xs-offset-4" %>
        <% end %>

      <script>
      $(function() {
          $('#image_btn').on('change', function(e) {
              // 1枚だけ表示する
              var file = e.target.files[0];
              console.log(file);
              if ( !file ){
                  $('#image_view').html("");
                  $('#orgin_img').show();
                  return;
              }
              // ファイルリーダー作成
              var fileReader = new FileReader();
              if (file.type == 'video/mp4') {
                  var dom = $("<video>");
              }
              else{
                  var dom = $("<img>");
              }
              dom.attr('style','width:20%');
              fileReader.onload = function() {
                  // Data URIを取得
                  console.log(this.result);
                  var dataUri = this.result;
                  dom.attr('src', dataUri);
                  // img要素に表示
                  $('#image_view').html(dom);
              }
              // ファイルをData URIとして読み込む
              fileReader.readAsDataURL(file);
              $('#orgin_img').hide();
          });
      });
      </script>

      <!-- 評価javascript -->
      <script>
      $('#star').raty({
        size     : 36,
        starOff:  '<%= asset_path('star-off.png') %>',
        starOn : '<%= asset_path('star-on.png') %>',
        starHalf: '<%= asset_path('star-half.png') %>',
        scoreName: 'music[rate]',
        half: true,
      });
      </script>

<%= link_to "一覧へ戻る",musics_path, class: "btn btn-primary col-xs-4 col-xs-offset-4" %>

  </div>
</div>

app/views/musics/index.html.erb
<div class="body">
  <div class="container">

<button type="button" class="btn btn-default btn-lg"><%= link_to '新規投稿', new_music_path,:style=>"color:red;" %></button>


<%= render '/musics/genre', genres: @genres %>

<div class='col-xs-10'>
      <h2>アルバム一覧</h2>
      <table class="table table-hover">
          <thead>
            <tr>
              <th>ジャケット</th>
              <th>アーティスト</th>
              <th>アルバム</th>
              <th>評価</th>
              <th>コメント</th>
            </tr>
          </thead>
          <tbody>
            <% @musics.each do |music|%>
              <tr>
                <td>
                    <%= attachment_image_tag music, :album_image, :fill, 150, 150, fallback: "no_image.jpg" ,size:'100x100'%>
                </td>
                <td><%= music.singer %></td>
                <td><%= link_to music.album,music_path(music),:style=>"color:red;" %></td>
                  <!--星評価-->
                <td>
                  <div id="star-rate-<%= music.id %>"></div>
                  <script>
                  $('#star-rate-<%= music.id %>').raty({
                    size: 36,
                    starOff:  '<%= asset_path('star-off.png') %>',
                    starOn : '<%= asset_path('star-on.png') %>',
                    starHalf: '<%= asset_path('star-half.png') %>',
                    half: true,
                    readOnly: true,
                    score: <%= music.rate %>,
                  });
                  </script>
                <!--/星評価-->
                </td>
                <td>
                <%=  "#{music.comments.count} コメント" %>
                </td>
              </tr>
            <%end%>
          </tbody>
        </table>
        <%= paginate @musics %>
    </div>
  </div>
</div>

app/views/musics/new.html.erb
<div class="body">
  <div class="container">

    <% if @music.errors.any? %>
      <div id="error_explanation">
        <h3><%= @music.errors.count %> 件のエラーがあります:</h3>
        <ul>
          <% @music.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

<h2 align="center">アルバム投稿</h2>
      <%= form_for(@music) do |f| %>
      <div class="row">
            <b>アルバム画像</b>
            <div id="image_view"></div>
            <%= attachment_image_tag @music, :album_image, :fill, 250, 250, fallback: "no_image.jpg", id:"orgin_img" %>
           <label for="image_btn">
            <%= f.attachment_field :album_image, id: "image_btn" %>
           </label>
        </div>
            <table class="table">
              <div class='col-xs-9'>
                <tbody>
                  <tr>
                    <td><b>アーティスト名</b></td>
                    <td><%= f.text_field :singer,placeholder: "アーティスト名入力" %></td>
                  </tr>
                  <tr>
                    <td><b>アルバム名</b></td>
                    <td><%= f.text_field :album,placeholder: "アルバム名入力" %></td>
                  </tr>
                  <tr>
                  <td><b>ジャンル</b></td>
                  <td><%= f.collection_select :genre_id, Genre.all, :id, :name, :include_blank => "-- 選択してください --" %></td>
                  </tr>

                  <tr>
                  <!-- 評価 -->
                    <td>
                      <div class="form-group row" id="star">
                          <%= f.label :rate,'評価', class:'col-md-1 col-form-label' %>
                          <%= f.hidden_field :rate, id: :review_star %>
                      </div>
                    </td>
                    </tr>
                  <tr>
                    <td><b>YouTubeのURL</b></td>
                    <td><%= f.text_area :url,placeholder: "URL入力" %></td>
                  </tr>
                  <tr>
                    <td><b>レビュー内容</b></td>
                    <td><%= f.text_area :introduction,placeholder: "レビュー内容" %></td>
                  </tr>
              </tbody>
             </div>
            </table>
            <%= f.submit '投稿する',class: "btn btn-success col-xs-4 col-xs-offset-4" %>
        <% end %>

      <script>
      $(function() {
          $('#image_btn').on('change', function(e) {
              // 1枚だけ表示する
              var file = e.target.files[0];
              console.log(file);
              if ( !file ){
                  $('#image_view').html("");
                  $('#orgin_img').show();
                  return;
              }
              // ファイルリーダー作成
              var fileReader = new FileReader();
              if (file.type == 'video/mp4') {
                  var dom = $("<video>");
              }
              else{
                  var dom = $("<img>");
              }
              dom.attr('style','width:20%');
              fileReader.onload = function() {
                  // Data URIを取得
                  console.log(this.result);
                  var dataUri = this.result;
                  dom.attr('src', dataUri);
                  // img要素に表示
                  $('#image_view').html(dom);
              }
              // ファイルをData URIとして読み込む
              fileReader.readAsDataURL(file);
              $('#orgin_img').hide();
          });
      });
      </script>

      <!-- 評価javascript -->
      <script>
      $('#star').raty({
        size     : 36,
        starOff:  '<%= asset_path('star-off.png') %>',
        starOn : '<%= asset_path('star-on.png') %>',
        starHalf: '<%= asset_path('star-half.png') %>',
        scoreName: 'music[rate]',
        half: true,
      });
      </script>

<%= link_to "一覧へ戻る",musics_path, class: "btn btn-primary col-xs-4 col-xs-offset-4" %>

  </div>
</div>

app/views/musics/show.html.erb
<div class="body">
  <div class="container">
          <div class='row'>
            <div class='col-xs-3'>
              <h1>ユーザー</h1>
                        <%= attachment_image_tag @user, :profile_image, :fill, 150, 150, fallback: "no_image.jpg" ,size:'150x150'%>
                    <table class="table">
                        <tr>
                            <td><p>name</p></td>
                            <td><p><%= link_to @user.name,user_path(@user),:style=>"color:red;" %></p></td>
                        </tr>
                        <tr>
                            <td><p>introduction</p></td>
                            <td><p><%= @user.introduction %></p></td>
                        </tr>
                    </table>

                    <p><%= "フォロー数: #{@user.follower.count}" %></p>
                    <p><%= "フォロワー数: #{@user.followed.count}" %></p>
                    <% unless @user == current_user %>
                       <% if current_user.following?(@user) %>
                       <%= link_to 'フォロー外す', unfollow_path(@user.id), method: :POST,class: "btn btn-danger" %>
                       <% else %>
                       <%= link_to 'フォローする', follow_path(@user.id), method: :POST,class: "btn btn-warning" %>
                       <% end %>
                    <% end %>
            </div>

         <div class='col-xs-9'>
              <table class="table">
                <h1>アルバム</h1>
                <tbody>
                      <tr>
                          <th>ジャケット:<h3><%= attachment_image_tag @music, :album_image, :fill, 200, 200, format: 'jpg',fallback: "no_image.jpg" ,size:'200x200'%></h3></th>
                      </tr>
                      <tr>
                          <th>アルバム:<h3><%= @music.album %></h3></th>
                      </tr>
                      <tr>
                          <th>アーティスト:<h3><%= @music.singer %></h3></th>
                      </tr>
                      <tr>
                          <th>ジャンル:<h3><%= @music.genre.name %></h3></th>
                      </tr>
                      <tr>
                        <th>評価:<h3><div id="star-rate-<%= @music.id %>"></h3></div>
                        <script>
                        $('#star-rate-<%= @music.id %>').raty({
                          size: 36,
                          starOff:  '<%= asset_path('star-off.png') %>',
                          starOn : '<%= asset_path('star-on.png') %>',
                          starHalf: '<%= asset_path('star-half.png') %>',
                          half: true,
                          readOnly: true,
                          score: <%= @music.rate %>,
                        });
                        </script>
                      <!--/星評価-->
                        </th>
                      </tr>
                      <tr>
                          <th>ユーザーコメント:<h3><%= @music.introduction %></h3></th>
                      </tr>
                      <tr>
                          <th>視聴先URL:<h3><%= Rinku.auto_link(@music.url, :all, 'target="_blank"').html_safe %></h3></th>
                      </tr>
                </tbody>
              </table>
       </div>
  <div class="text-right">
    <div class="favorite-link" id="favorite-link-<%= @music.id %>">
      <%= render 'favorites/favorites', music:@music %>
    </div>
  </div>

<!-- コメント機能 -->
    <div class="row">
              <div class="comment-list bt style-2" id="comments">
                  <h2 class="comment-count"><%= @music.comments.count %>件コメント</h2>
                  <% @music.comments.each do |comment| %>
                          <%= attachment_image_tag comment.user, :profile_image, :fill, 150, 150, fallback: "no_image.jpg",size:'100x100' %>
                          <%= comment.user.name %>
                          <%= comment.created_at.strftime('%Y/%m/%d') %>
                          <h4><%= comment.comment %></h4>
                          <!-- <h4><%= comment.score %></h4> -->
                          <!-- Google Natural Language API -->
                          <div class="icon">
                            <% if comment.score.present? %>
                              <% if comment.score * 10 <= -5 %>
                                <i class="far fa-sad-cry fa-lg"></i>
                              <% elsif comment.score * 10 < 0.0 %>
                                <i class="far fa-frown-open fa-lg"></i>
                              <% elsif comment.score * 10 <= 5 %>
                                <i class="far fa-smile-wink fa-lg"></i>
                              <% elsif comment.score * 10 <= 10 %>
                                <i class="far fa-grin-beam fa-lg"></i>
                              <% else %>
                                <i class="far fa-meh fa-lg"></i>
                              <% end %>
                            <% end %>
                          </div>
                  <% end %>
              </div>

              <div class="section-title-wrapper style-1 v1 mt-30" id="divAddComment">
                <h3 class="section-title left">
                  <span>コメント</span>
                </h3>
              </div>
              <%= form_for [@music, @comment] do |f| %>
              <div class="row">
                 <div class="col-sm-12">
                 <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
                 </div>
              </div>
              <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
              <% end %>

    </div>
    <!-- ここまで -->

  </div>
</div>

app/views/musics/top.html.erb
musics#top
<% if user_signed_in? %>
<%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
ログイン中
<%= link_to 'アバウト', musics_about_path %>
<% else %>
<%= link_to 'ログイン', new_user_session_path %>
ログアウト中
<% end %>

app/views/users/index.html.erb
<div class="body">
  <div class="container">

        <div class='col-xs-12'>
          <h2>ユーザー一覧</h2>
            <table class="table">
                <thead>
                   <tr>
                      <th>プロフィール画像</th>
                      <th>名前</th>
                      <th>プロフィール</th>
                   </tr>
                </thead>
                <tbody>
                    <% @users.each do |user| %>
                      <tr>
                        <td><%= attachment_image_tag user, :profile_image, :fill, 150, 150, fallback:'no_image.jpg' , size:'100x100' %></td>
                        <td><%= link_to user.name,user_path(user),:style=>"color:red;" %></td>
                        <td><%= user.introduction %></td>
                      </tr>
                    <% end %>
                </tbody>
            </table>
            <%= paginate @users %>
        </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="body">
    <div class="container">
 <div class='row'>
                <div class='col-xs-3'>
                <h1>ユーザー</h1>
                        <%= attachment_image_tag @user, :profile_image, :fill, 150, 150, fallback: "no_image.jpg" ,size:'150x150'%>
                    <table class="table">
                        <tr>
                            <td><p>ユーザー名</p></td>
                            <td><p><%= @user.name %></p></td>
                        </tr>
                        <tr>
                            <td><p>プロフィール</p></td>
                            <td><p><%= @user.introduction %></p></td>
                        </tr>
                    </table>

                    <% if @user.id == current_user.id %>
                          <%= link_to 'プロフィール編集', edit_user_path(@user.id), class: "btn btn-warning btn-sm btn-block" %>
                    <% end %>
                </div>

                <div class='col-xs-9'>
                <h2>投稿一覧</h2>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>ジャケット</th>
                                <th>アルバム</th>
                                <th>アーティスト</th>
                                <th></th>
                                <th></th>

                            </tr>
                        </thead>
                        <tbody>
                            <% @user.musics.each do |music| %>
                              <tr>
                                <td><%= link_to user_path(music.user.id) do %>
                                    <%= attachment_image_tag music, :album_image, :fill, 150, 150, fallback: 'no_image.jpg' , size:'80x80' %>
                                        <% end %>
                                    </td>
                                <td><%= link_to music.album,music_path(music),:style=>"color:red;" %></td>
                                <td><%= music.singer %></td>
                                <% if user_signed_in? && music.user_id == current_user.id %>
                                <td><%= link_to '編集する', edit_music_path(music), class: "btn btn-primary" %></td>
                                <td><%= link_to '削除する', music_path(music), method: :delete, "data-confirm" => "投稿を削除してよろしいですか?", class: "btn btn-danger" %></td>
                                <% end %>
                              </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>

        <div class='row'>
            <div class='col-xs-3'>
                <p><%= "フォロー: #{@user.follower.count}" %></p>
                <p><%= "フォロワー: #{@user.followed.count}" %></p>
                <% unless @user == current_user %>
                  <% if current_user.following?(@user) %>
                    <%= link_to 'フォロー外す', unfollow_path(@user.id), method: :POST,class: "btn btn-danger" %>
                  <% else %>
                    <%= link_to 'フォローする', follow_path(@user.id), method: :POST,class: "btn btn-warning" %>
                  <% end %>
                <% end %>
          </div>
          <div class='col-xs-9'>
              <h3>フォロー一覧</h3>
              <% @user.following_user.where.not(id: current_user.id).each do |user| %>
                <p>
                  <%= "ユーザー名: #{user.name}" %>
                  <% if current_user.following?(user) %>
                    <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST,class: "btn btn-danger btn-sm" %>
                  <% else %>
                    <%= link_to 'フォローする', follow_path(user.id), method: :POST,class: "btn btn-warning btn-sm" %>
                  <% end %>
                  <%= link_to "ユーザーページへ", user_path(user),class: "btn btn-default btn-sm" %>
                </p>
              <% end %>
            <h3>フォロワー一覧</h3>
              <% @user.follower_user.where.not(id: current_user.id).each do |user| %>
                <p>
                  <%= "ユーザー名: #{user.name}" %>
                  <% if current_user.following?(user) %>
                    <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST,class: "btn btn-danger btn-sm" %>
                  <% else %>
                    <%= link_to 'フォローする', follow_path(user.id), method: :POST,class: "btn btn-warning btn-sm" %>
                  <% end %>
                  <%= link_to "ユーザーページへ", user_path(user),class: "btn btn-default btn-sm" %>
                </p>
              <% end %>
          </div>
      </div>

  </div>
</div>