config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'homes#top'
  get  'homes/about' => 'homes#about'
  post   '/favorite/:music_id' => 'favorites#favorite',   as: 'favorite'
  delete '/favorite/:music_id' => 'favorites#unfavorite', as: 'unfavorite'
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す

  resources :musics do
  	resource :comments, only: [:create]
  end
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :user
    belongs_to :music
end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :music, counter_cache: :favorites_count
    belongs_to :user
end

app/models/genre.rb
class Genre < ApplicationRecord

	has_many :musics
end

app/models/music.rb
class Music < ApplicationRecord

	belongs_to :genre
	belongs_to :user
    has_many :favorites, dependent: :destroy
	attachment :album_image
	has_many :comments, dependent: :destroy

    validates :singer, presence: true
    validates :album, presence: true
    validates :rate, presence: true
    validates :url, presence: true
    validates :introduction, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord

	belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :musics
  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorite_musics, through: :favorites, source: :music

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  attachment :profile_image

  validates :name, presence: true
  validates :introduction, length: { maximum: 55 }

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		music = Music.find(params[:music_id])
	    comment = current_user.comments.new(comment_params)
	    comment.music_id = music.id
	    comment.score = Language.get_data(comment_params[:comment])
	    comment.save
	    redirect_to music_path(music)
	end

	private
	def comment_params
	    params.require(:comment).permit(:user_id,:music_id,:comment)
	end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

	def top
	end

	def about
	end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController

	before_action :authenticate_user!

	def index
		if params[:genre_id]
	      # Genreのデータベースのテーブルから一致するidを取得
	      @genre = Genre.find(params[:genre_id])
	      # genre_idと紐づく投稿を取得
	      @musics = @genre.musics.order(created_at: :desc).page(params[:page]).per(3)
	    else
	      # 投稿すべてを取得
	      @musics = Music.order(created_at: :desc).page(params[:page]).per(3)

	    end
	      @genres = Genre.all
	end

	def new
		@music = Music.new
	end

	def show
		@music = Music.find(params[:id])
        @comment = Comment.new
        @user = @music.user
	end

	def create
	    @music = Music.new(music_params)
	    @music.user_id = current_user.id
	 if @music.save
		redirect_to musics_path
	 else
		render 'new'
	 end
	end

	def edit
		@music = Music.find(params[:id])
	end

	def update
        @music = Music.find(params[:id])
     if @music.update(music_params)
        redirect_to musics_path
     else
        render 'edit'
     end
    end

    def destroy
       music = Music.find(params[:id])
       music.destroy
       redirect_to musics_path(@music)
    end

	private
    def music_params
        params.require(:music).permit(:singer, :album, :album_image, :introduction, :user_id, :rate, :url, :genre_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!

	def index
		user = current_user
		@users = User.page(params[:page]).per(3).order('updated_at DESC')
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
    if  @user.id != current_user.id
        redirect_to user_path(current_user)
    end
	end

	def update
		@user = User.find(params[:id])
	if  @user.update(user_params)
	    redirect_to user_path(@user.id)
	else
	    render 'edit'
	end
	end

 private
	def user_params
	    params.require(:user).permit(:name, :profile_image,:introduction)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music Research</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
<body>
<nav class="navbar navbar-default sticky-top">
  <div class="container-fluid">

    <% if user_signed_in? %>

    <div class="navbar-header">
      <a class="navbar-brand" href="/musics">
        Music Research
      </a>
    </div>

    <% else %>

    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        Music Research
      </a>
    </div>

    <% end %>

    <div class="collapse navbar-collapse navbar-right" id="navbarEexample">
      <ul class="nav navbar-nav">

        <% if user_signed_in? %>
         <li><%= link_to 'ユーザーを探す', users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">ジャンル <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <td><%= link_to '全て', musics_path %></td>
                </li>
                <% Genre.all.each do |genre| %>
                <li>
                  <td><%= link_to genre.name, "/musics?genre_id=#{genre.id}" %></td>
                </li>
                <% end %>
              </ul>
            </li>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" role="button">こんにちは <%= current_user.name %> <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to 'マイページ', user_path(current_user) %></li>
                  <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>

        <% else %>
                  <li><%= link_to 'アバウト',  homes_about_path %></li>
                  <li><%= link_to 'ログイン', new_user_session_path %></li>
                  <li><%= link_to '新規登録', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

    <%= yield %>

    <footer class="footer">
      <div>
        <p>© Music Research. ALL RIGHTS RESERVED</p>
      </div>
  　</footer>

  </body>
</html>